### ISSUE TITLE
安装了线上版本， 发现尺寸有点大

### ISSUE THREAD

**Issue by cyrilis** [pili-engineering/PLLiving#11]
Hi there, 
在 App Store 上安装了  Living 客户端， 发现尺寸大小为 215 MB， 感觉有点大。请问是因为 SDK 的原因还是别的什么问题？

**Comment by moskize** [comment]
SDK 很小的。之所以尺寸很大，是因为里面的送礼动画资源文件没有优化导致的。

**Comment by cyrilis** [comment]
好的明白了，谢谢 😄
